In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
  print(f"GPU is available!")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")

else:
  print(f"GPU not availabel. using CPU!")

GPU is available!
using GPU: Tesla T4


# Creating a Tensor

In [3]:
# using empty
a = torch.empty(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2, 3)

tensor([[0.7517, 0.4055, 0.4336],
        [0.0248, 0.1388, 0.5177]])

In [8]:
# manual_seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# other ways
# arange
print("using arange -> ", torch.arange(0, 10, 2))

# suing linspace
print("using linspace -> ", torch.linspace(0, 10, 10)) # 1d array with 0 to 10 values evenly

# using eye
print("using eye -> ", torch.eye(5)) # identity matrix

# using full
print("using full -> ", torch.full((3, 5), 10)) # 3 by 5 matrix fill with 10

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


# Tensor Shape

In [11]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.shape # [2, 3] 2 rows, 3 column

torch.Size([2, 3])

In [12]:
torch.empty_like(x) # copy the shape of x. values will be different

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7148961061476054114]])

In [13]:
torch.zeros_like(x) # same shape of x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [14]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [15]:
torch.rand_like(x, dtype=torch.float32) # gives error. because x is integer. but rand generate float


tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [16]:
# find data type
x.dtype

torch.int64

In [17]:
# tensor data type at creation
# float to integer
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
# integer to float
torch.tensor([1, 2, 3], dtype=torch.float32)

tensor([1., 2., 3.])

In [19]:
# using to()
y = torch.empty(2, 3)
y

y.to(torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

# Mathematical operations

## 1. Scaler operation

In [20]:
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [21]:
# addition
x + 2

# subtruction
x - 2

# multiplication
x * 2

# division

x / 3

# int division

(x * 100 ) // 3

# mod
(((x * 100))//3)%2

# power
x ** 2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

## 2. Element wise operation

In [22]:
# Note: shape must be same
a = torch.rand(2, 3)
b = torch.rand(2, 3)


print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [23]:
# addition
a + b

# subtruction
a - b

# multiplication
a * b

# division
a / b

# power
a ** b

# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

## Atomic operation

In [24]:
# abs
c = torch.tensor([1, -2, 3, 9, -4])
torch.abs(c)

tensor([1, 2, 3, 9, 4])

In [25]:
# round
d = torch.tensor([2.0, 3.2, 9.234])
torch.round(d)

tensor([2., 3., 9.])

In [26]:
# floor
torch.floor(d)

tensor([2., 3., 9.])

In [27]:
# ceil
torch.ceil(d)

tensor([ 2.,  4., 10.])

In [28]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2., 3., 3.])

# Reduction operation

In [29]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [30]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum alogn row
torch.sum(e, dim=1)

tensor([15,  9])

In [31]:
# mean (must tensor float)
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
f

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [32]:
# mean row
print(torch.mean(f, dim=0))

# mean column
print(torch.mean(f, dim=1))

# mean
print(torch.mean(f))

tensor([7.0000, 5.5000, 1.5000])
tensor([5.0000, 4.3333])
tensor(4.6667)


In [33]:
# median, min, max, product, standard deviation, variance, armax
print(torch.median(f))

print(torch.min(f))

print(torch.max(f))

print(torch.prod(f))

print(torch.std(f))

print(torch.var(f))

print(torch.argmax(f))

print(torch.argmin(f))



tensor(4.)
tensor(0.)
tensor(9.)
tensor(0.)
tensor(3.1411)
tensor(9.8667)
tensor(3)
tensor(5)


# matrix, vector

In [34]:
# matrix multiplication
x = torch.randint(size=(2,3), low=2, high=9)
y = torch.randint(size=(3,2), low=1, high=10)

ans = torch.matmul(x, y)
print(ans)

tensor([[76, 36],
        [74, 39]])


In [35]:
# dot product
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])

ans = torch.dot(x, y)
print(ans)

tensor(11)


In [36]:
# transpose
a = torch.randint(size=(2, 3), low=1, high=10)
print(a)


print(torch.transpose(a, 0, 1))


tensor([[4, 6, 6],
        [6, 1, 4]])
tensor([[4, 6],
        [6, 1],
        [6, 4]])


In [37]:
# determinent
m = torch.randint(size=(3, 3), low=1, high=10, dtype=torch.float32)
print(torch.det(m))

# inverse
print(torch.inverse(m))


tensor(42.0000)
tensor([[-0.1429,  0.0952,  0.2381],
        [ 0.7143, -0.6429,  0.1429],
        [-0.1429,  0.2619, -0.0952]])


In [38]:
# matrix comparision
i = torch.randint(size=(2, 3), low=2, high=10)
j = torch.randint(size=(2, 3), low=1, high=20)

# less than equal
print(i<j)

# greater than
print(i>j)

# greater than equal
print(i>=j)

# less than equal
print(i<=j)

# equal to
print(i==j)



tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [False, False,  True]])
tensor([[ True, False, False],
        [False, False,  True]])
tensor([[False,  True,  True],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False, False]])


# Special functions

In [39]:
k = torch.randint(size=(2, 3), low=2, high=10, dtype=torch.float32)
print(k)

tensor([[2., 7., 4.],
        [8., 3., 7.]])


In [40]:
# log
print(torch.log(k))

tensor([[0.6931, 1.9459, 1.3863],
        [2.0794, 1.0986, 1.9459]])


In [41]:
# exp
print(torch.exp(k))

tensor([[   7.3891, 1096.6332,   54.5981],
        [2980.9580,   20.0855, 1096.6332]])


In [42]:
# sqrt
print(torch.sqrt(k))

tensor([[1.4142, 2.6458, 2.0000],
        [2.8284, 1.7321, 2.6458]])


In [43]:
# sigmoids
print(torch.sigmoid(k))

tensor([[0.8808, 0.9991, 0.9820],
        [0.9997, 0.9526, 0.9991]])


In [44]:
# softmax
print(torch.softmax(k, dim=0))

tensor([[0.0025, 0.9820, 0.0474],
        [0.9975, 0.0180, 0.9526]])


In [45]:
# relu
print(torch.relu(k))

tensor([[2., 7., 4.],
        [8., 3., 7.]])


# Inplace Operations

In [46]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)

print(n)

# element wise addition (it makes new memory location. it is problem for huge dataset)
print(m+n)

# we can store result into m or n
print(m.add_(n))

print(m) # it will show result

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])
tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])
tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])


In [47]:
# similarly if we do relu on tensor, it makes new storage
print(torch.relu(m))

# we can use reul_. here underscore is inplace operation means store result into that memory
print(m.relu_())

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])
tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])


# copying tensor

In [48]:
a = torch.rand(2, 3)
print(a)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [49]:
# copy using reference. if we change in a, automatically b will be changed
b = a
print(b)

a[0][0] = 100
print(a)

print(b)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[100.0000,   0.2131,   0.3957],
        [  0.6017,   0.4234,   0.5224]])
tensor([[100.0000,   0.2131,   0.3957],
        [  0.6017,   0.4234,   0.5224]])


In [50]:
print(id(a))

print(id(b))

133319193222544
133319193222544


In [51]:
# copy using clone
x = torch.clone(a)

print(x)

a[0][0] = 3

print(x)

print(a)

# both different location
print(id(a))
print(id(x))

tensor([[100.0000,   0.2131,   0.3957],
        [  0.6017,   0.4234,   0.5224]])
tensor([[100.0000,   0.2131,   0.3957],
        [  0.6017,   0.4234,   0.5224]])
tensor([[3.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
133319193222544
133319192776912


# Tensor on GPU

In [52]:
currentDevice = torch.cuda.is_available()
print(currentDevice)

True


In [53]:
# creating a tensor on GPU
device = torch.device('cuda')
a = torch.rand((2, 3), device=device)
print(a)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')


In [54]:
# move existing tensor to GPU
m = torch.rand(2, 3)
print(m)

new = m.to(device)

print(new)

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]], device='cuda:0')


# CPU vs GPU Performance tesnting

In [55]:
# same size matrix multiplication on cpu and gpu and calculate time
import time

# define the size of the matrix
size = 10000

# create two random matrix
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.rand(size, size)

# measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time} seconds")


# move matrix to GPU
matrix_gpu1 = matrix_cpu1.to(device)
matrix_gpu2 = matrix_cpu2.to(device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize() # ensure all GPU operations are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time} seconds")


# compare result
print(f"\nSpeedup (CPU time / GPU time): {cpu_time / gpu_time}")


Time on CPU: 23.4997341632843 seconds
Time on GPU: 0.6798923015594482 seconds

Speedup (CPU time / GPU time): 34.563906826689575


# Reshaping Tensors

In [56]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [58]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [59]:
b = torch.rand(2, 3, 4)
print(b)

tensor([[[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]],

        [[0.2861, 0.7459, 0.8487, 0.4059],
         [0.2883, 0.2220, 0.6423, 0.7098],
         [0.5644, 0.4549, 0.0729, 0.8535]]])


In [60]:
# permute
b.permute(2, 0, 1)

tensor([[[0.1174, 0.7907, 0.5839],
         [0.2861, 0.2883, 0.5644]],

        [[0.6532, 0.7351, 0.0061],
         [0.7459, 0.2220, 0.4549]],

        [[0.5115, 0.2693, 0.4671],
         [0.8487, 0.6423, 0.0729]],

        [[0.3094, 0.8009, 0.8243],
         [0.4059, 0.7098, 0.8535]]])

In [63]:
# unsqueeze
# image size
c = torch.rand(226, 226, 3)

c.unsqueeze(0).shape
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

# Numpy and PyTorch

In [64]:
import numpy as np

In [65]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [66]:
# tensor to numpy convert
b = a.numpy()
b

array([1, 2, 3])

In [67]:
type(b)

numpy.ndarray

In [69]:
c = np.array([1, 2, 3])
print(c)
type(c)

[1 2 3]


numpy.ndarray

In [71]:
# convert numpy to tensor
x = np.array([10, 20, 30])
x

array([10, 20, 30])

In [ ]:
torch.fr