# Create simple model
1. Load the dataset

2. Basic preprocessing

3. Training Process

  a. Create the model

  b. Forward pass

  c. Loss calculation

  d. Backward
  
  e. Parameters update

4. Model evaluation (accuracy, precision, recall, F1)


In [18]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [19]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
print(df.shape)

df.head() # see the data

(569, 33)


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [20]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

# Train test split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)


In [23]:
X_train

array([[-0.82260768, -0.87715671, -0.77815143, ..., -0.50078948,
        -1.1868077 ,  1.09214661],
       [-0.63446503, -0.25374508, -0.68348306, ..., -0.80133007,
        -0.19153745, -0.54315179],
       [-0.27783643,  1.98052579, -0.3109041 , ..., -0.54854745,
        -0.68600293, -1.06534337],
       ...,
       [ 0.80328179,  0.37421699,  0.78286097, ...,  1.01986073,
        -0.44827914, -0.43979574],
       [ 0.06194358, -0.64053332,  0.06573788, ...,  0.39170656,
         0.23319571,  0.19062208],
       [ 0.54212856, -0.33565318,  0.58783599, ...,  1.07613604,
         2.16192803,  2.12029584]])

In [24]:
y_train

388    B
52     B
543    B
208    B
103    B
      ..
389    M
332    B
335    M
340    B
34     M
Name: diagnosis, Length: 455, dtype: object

In [25]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,

# Numpy arrays to PyTorch tensors

In [26]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(y_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [27]:
X_train_tensor.shape

torch.Size([455, 30])

# Defining the model

In [28]:
class MySimpleNN():
  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    #lamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


# Important parameters

In [29]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [30]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)
  print(y_pred)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)



  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()


  # print loss in each epoch
  print(f"epoch: {epoch + 1}, Loss: {loss.item()}")





Streaming output truncated to the last 5000 lines.
        [0.2717],
        [0.9195],
        [0.6423],
        [0.0685],
        [0.7707],
        [0.1160],
        [0.0857],
        [0.1497],
        [0.7951],
        [0.8703],
        [0.8037],
        [0.4198],
        [0.4714],
        [0.1583],
        [0.7273],
        [0.6567],
        [0.0100],
        [0.0668],
        [0.9500],
        [0.0954],
        [0.0270],
        [0.0710],
        [0.1131],
        [0.0131],
        [0.2560],
        [0.9802],
        [0.2024],
        [0.6529],
        [0.9769],
        [0.4866],
        [0.0107],
        [0.1717],
        [0.4433],
        [0.0780],
        [0.3748],
        [0.9544],
        [0.9880],
        [0.0161],
        [0.8243],
        [0.0632],
        [0.9815],
        [0.1935],
        [0.0117],
        [0.4722],
        [0.9678],
        [0.0712],
        [0.5099],
        [0.7169],
        [0.4044],
        [0.1207],
        [0.8597],
        [1.0000],
        [0.06

In [31]:
model.bias

tensor([-0.1320], dtype=torch.float64, requires_grad=True)

# model evaluation

In [35]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_train_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5377482175827026
