# Simple neural network using PyTorch nn module (single neuron)

# Improvements

1. Building the neural network using nn module

2. Using built-in activation function

3. Using built-in loss function

4. Using built-in optimizer

In [1]:
# create model class
import torch
import torch.nn as nn


class Model(nn.Module): #extend nn module to use inside my model

  def __init__(self, num_features):
    super().__init__() # nn.module class invoked
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features) # z = wx+b
    out = self.sigmoid(out) # prediction sigmoid(z)
    return out


In [2]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features) # similar to model.forward(features)


tensor([[0.5560],
        [0.5500],
        [0.5393],
        [0.5003],
        [0.4948],
        [0.5635],
        [0.5812],
        [0.5326],
        [0.5364],
        [0.5609]], grad_fn=<SigmoidBackward0>)

In [3]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.4022, -0.1436,  0.0743, -0.2546,  0.3397]], requires_grad=True)

In [4]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.4134], requires_grad=True)

# model info using torchinfo

In [5]:
!pip install torchinfo

In [6]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Complex neural network. 5 neurons input layer, 3 neurons hidden layer and one neuron in output layer

hidden layer relu and output layer sigmoid

In [7]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()

    self.linear1 = nn.Linear(num_features, 3) # input: features, output: 3 neurons
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)

    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [8]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4866],
        [0.5054],
        [0.4679],
        [0.5222],
        [0.4930],
        [0.4991],
        [0.4881],
        [0.4930],
        [0.4889],
        [0.4715]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear1.weight

Parameter containing:
tensor([[ 0.4280,  0.3007, -0.4247,  0.0719, -0.0166],
        [-0.3965,  0.3451,  0.4454, -0.4044,  0.4087],
        [-0.4443, -0.2806,  0.3533,  0.0418, -0.3719]], requires_grad=True)

In [10]:
model.linear2.weight

Parameter containing:
tensor([[-0.0249, -0.3119,  0.3948]], requires_grad=True)

In [11]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential neural network

In [12]:
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential (
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
      )



  def forward(self, features):
    out = self.network(features)
    return out


In [13]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.4709],
        [0.4724],
        [0.4718],
        [0.4533],
        [0.4520],
        [0.4625],
        [0.4314],
        [0.4829],
        [0.4541],
        [0.4693]], grad_fn=<SigmoidBackward0>)

# Training pipeline with real data using nn module

In [14]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn


df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.shape

(569, 33)

In [15]:
# import necessary libary functions
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


print(df.shape)

df.head()

(569, 33)


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [16]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

print(df.shape)
df.head()

(569, 31)


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

# Train test split and preprocessing

In [17]:
# train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.3)

# preprocessing
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)


print(X_train)

y_train

[[-0.03536551 -1.43629888 -0.05260207 ... -0.2244434  -1.21881829
  -0.65415924]
 [-0.3774847  -0.5903376  -0.37779943 ... -0.54234203  0.24734153
   0.062392  ]
 [-0.69660429 -0.19970958 -0.68381849 ...  0.08212868 -0.17914843
   0.35912335]
 ...
 [-0.2481119  -0.80122879 -0.31275996 ... -1.37975197 -0.42860482
  -0.03212242]
 [ 2.71596278  1.22380601  2.64862065 ...  1.39751921 -0.52194979
  -0.38765053]
 [-0.25673675 -0.12062538 -0.2331283  ...  1.39600901  1.58153087
   1.83893355]]


528    B
519    B
106    B
194    M
504    B
      ..
255    M
552    B
306    B
339    M
47     M
Name: diagnosis, Length: 398, dtype: object

In [18]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

print(y_train)

print(y_test)

[0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0
 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1
 0 1 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1
 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1
 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 1 1 0 1 0 0 0 1 1 1 0 0 0
 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0
 0 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 1 1 0
 1 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 1 1]
[1 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0
 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0
 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 0 0 0 1

In [19]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [20]:
X_train_tensor.shape

torch.Size([398, 30])

In [21]:
y_train_tensor.shape

torch.Size([398])

# Define model

In [27]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


# Importants parameters

In [28]:
learning_rate = 0.1
epochs = 25

In [29]:
loss_function = nn.BCELoss()
type(loss_function)

torch.nn.modules.loss.BCELoss

# Training the model

In [35]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])


# define optimzer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

  # gradient clear
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f"epoch: {epoch + 1}, Loss: {loss.item()}")


epoch: 1, Loss: 0.8178201913833618
epoch: 2, Loss: 0.5798110365867615
epoch: 3, Loss: 0.4609181880950928
epoch: 4, Loss: 0.39305785298347473
epoch: 5, Loss: 0.3486703932285309
epoch: 6, Loss: 0.31693339347839355
epoch: 7, Loss: 0.29285648465156555
epoch: 8, Loss: 0.27381202578544617
epoch: 9, Loss: 0.25827571749687195
epoch: 10, Loss: 0.24529702961444855
epoch: 11, Loss: 0.23424963653087616
epoch: 12, Loss: 0.22470222413539886
epoch: 13, Loss: 0.2163471281528473
epoch: 14, Loss: 0.20895829796791077
epoch: 15, Loss: 0.20236551761627197
epoch: 16, Loss: 0.1964377909898758
epoch: 17, Loss: 0.19107261300086975
epoch: 18, Loss: 0.18618828058242798
epoch: 19, Loss: 0.1817188709974289
epoch: 20, Loss: 0.17761050164699554
epoch: 21, Loss: 0.17381857335567474
epoch: 22, Loss: 0.17030589282512665
epoch: 23, Loss: 0.16704104840755463
epoch: 24, Loss: 0.16399739682674408
epoch: 25, Loss: 0.16115209460258484


# Model evaluation

In [36]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_train_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5404654741287231
